### ISSUE TITLE
My german colleagues don't know how to clearfix

### ISSUE THREAD

**Issue by Xiphe** [timche/postcss-german-stylesheets#12]
afais, `beide` is not supported...

example code:

``` css
.probleme {
  klären: beide;
}
```

expected result

``` css
.probleme {
  clear: both;
}
```
